# Generated by Django 2.2.4 on 2020-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojos',
            name='email',
        ),
        migrations.AlterField(
            model_name='dojos',
            name='state',
            field=models.CharField(max_length=45),
        ),
    ]
