# Generated by Django 2.2.4 on 2020-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20200815_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='fname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='lname',
            field=models.CharField(max_length=255),
        ),
    ]
