# Generated by Django 2.2.4 on 2020-08-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20200815_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
