# Generated by Django 2.2.4 on 2020-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_quote_quotemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteManager',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
