# Generated by Django 2.2.4 on 2020-08-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0003_auto_20200824_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_quotes', to='belt_exam_app.User'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='liked_quotes', to='belt_exam_app.User'),
        ),
    ]
