# Generated by Django 2.2.4 on 2020-08-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0004_auto_20200825_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='dislikes',
        ),
    ]
